#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Kerv.Droid.Resource", IsApplication=true)]

namespace Kerv.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int device_list = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_padding = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int label_padding = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int transaction_padding = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int amountView = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int balanceLabel = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int balanceLayout = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int balanceView = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int dateView = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int descriptionView = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int deviceSpinner = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int loginProgress = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int passwordField = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int submitButton = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int transactionListView = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int usernameField = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TransactionListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
